require ('srpancakes.launch')
require ('srpancakes.options')
require ('srpancakes.keymaps')
spec ('srpancakes.colorscheme')
spec ('srpancakes.devicons')
spec ('srpancakes.treesitter')
spec ('srpancakes.mason')
spec ('srpancakes.schemastore')
spec ('srpancakes.lspconfig')
spec ('srpancakes.cmp')
spec ('srpancakes.autopairs')
-- spec ('srpancakes.none-ls')
require ('srpancakes.lazy')
